version: "2"

run:
  go: "1.25"
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-declaration
        - name: unused-parameter
